# Generated by Django 5.1.5 on 2025-03-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
