# Generated by Django 5.1.5 on 2025-03-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_propuesta', models.DateField(auto_now_add=True)),
                ('servicio_envio', models.CharField(default='TGZ', max_length=100, null=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_Civa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(default='No', max_length=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_8', models.BooleanField(default=False)),
                ('iva_16', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('phistorico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usar_precio_distribuidor', models.BooleanField(default=False)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizaciones.cotizaciones')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
