# Generated by Django 5.1.5 on 2025-01-29 23:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.CharField(default=1, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField(default=datetime.datetime.today)),
                ('fecha_propuesta', models.DateField(verbose_name=datetime.datetime.today)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizaciones.cotizaciones')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='product',
            field=models.ManyToManyField(through='cotizaciones.CotizacionProduct', to='products.product'),
        ),
    ]
