# Generated by Django 5.1.5 on 2025-01-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_propuesta',
            field=models.CharField(max_length=100),
        ),
    ]
