# Generated by Django 5.1.5 on 2025-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
