# Generated by Django 5.1.5 on 2025-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizaciones_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='cliente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
