# Generated by Django 5.1.5 on 2025-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizaciones_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='product',
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
