# Generated by Django 5.1.5 on 2025-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_alter_cotizaciones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='direccion_entrega',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha_entrega',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
