# Generated by Django 5.1.5 on 2025-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_remove_cotizaciones_product_alter_cotizaciones_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionproduct',
            name='phistorico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
