# Generated by Django 5.1.5 on 2025-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizaciones_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
