# Generated by Django 5.1.5 on 2025-02-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_cotizacionproduct_phistorico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionproduct',
            name='subtotal',
        ),
    ]
