# Generated by Django 5.1.5 on 2025-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_remove_cotizacionproduct_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
