# Generated by Django 5.1.5 on 2025-03-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_alter_cotizaciones_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='direccion_entrega',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_entrega',
            field=models.DateField(default='', null=True),
        ),
    ]
