# Generated by Django 5.1.5 on 2025-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_cotizacionproduct_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='status',
            field=models.CharField(default='En proceso', max_length=20),
        ),
    ]
