# Generated by Django 5.1.5 on 2025-03-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_alter_cotizaciones_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
