# Generated by Django 5.1.5 on 2025-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_cotizaciones_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='status',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
