# Generated by Django 5.1.5 on 2025-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizaciones_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='telefono',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
