# Generated by Django 5.1.5 on 2025-02-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('cotizaciones', '0008_alter_cotizaciones_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
