# Generated by Django 5.1.5 on 2025-02-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_cotizaciones_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciones',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
