# Generated by Django 5.1.5 on 2025-03-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_alter_cotizaciones_telefono'),
        ('products', '0006_alter_product_otro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega', models.IntegerField(default=0.0)),
                ('status', models.CharField(default='Pendiente', max_length=20)),
                ('cotizacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='cotizaciones.cotizaciones')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
