# Generated by Django 5.1.5 on 2025-03-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_remisiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='direccion_entrega',
            field=models.CharField(default='Pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
