# Generated by Django 5.1.5 on 2025-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_alter_cotizaciones_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='direccion_entrega',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='servicio_envio',
            field=models.CharField(default='TGZ', max_length=100),
        ),
    ]
