# Generated by Django 5.1.5 on 2025-02-13 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('cotizaciones', '0013_remove_cotizaciones_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
