# Generated by Django 5.1.5 on 2025-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_alter_cotizaciones_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_propuesta',
            field=models.DateField(),
        ),
    ]
