# Generated by Django 5.1.5 on 2025-03-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_alter_cotizaciones_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
