# Generated by Django 5.1.5 on 2025-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_remisiones_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='restante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
