# Generated by Django 5.1.5 on 2025-02-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_alter_cotizaciones_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='cliente_id',
        ),
    ]
