# Generated by Django 5.1.5 on 2025-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_remove_cotizaciones_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionproduct',
            name='estatico',
            field=models.BooleanField(default=False),
        ),
    ]
