# Generated by Django 5.1.5 on 2025-03-20 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_remisiones_restante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.IntegerField()),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='cotizaciones.remisiones')),
            ],
        ),
    ]
