# Generated by Django 5.1.5 on 2025-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_entregas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=16.0, help_text='Porcentaje de IVA (ejemplo: 8.00, 16.00)', max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='iva_16',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='iva_8',
        ),
    ]
