# Generated by Django 5.1.5 on 2025-02-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_cotizacionproduct_estatico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionproduct',
            name='estatico',
        ),
    ]
