# Generated by Django 5.1.5 on 2025-02-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0018_remove_cotizacionproduct_estatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionproduct',
            name='precio_usado',
            field=models.BigIntegerField(default=False),
        ),
    ]
