# Generated by Django 5.1.5 on 2025-02-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_cotizacionproduct_precio_usado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionproduct',
            name='precio_usado',
        ),
        migrations.AddField(
            model_name='cotizacionproduct',
            name='usar_precio_distribuidor',
            field=models.BooleanField(default=False),
        ),
    ]
