# Generated by Django 5.1.5 on 2025-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0020_remove_cotizacionproduct_precio_usado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='metodo_pago',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
