# Generated by Django 5.1.5 on 2025-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0021_cotizaciones_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='restante',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
