# Generated by Django 5.1.5 on 2025-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0022_cotizaciones_anticipo_cotizaciones_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='servicio_envio',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='total_Civa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
