# Generated by Django 5.1.5 on 2025-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_cotizaciones_costo_envio_cotizaciones_servicio_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='iva_16',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='iva_8',
            field=models.BooleanField(default=False),
        ),
    ]
