# Generated by Django 5.1.5 on 2025-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0024_cotizaciones_iva_16_cotizaciones_iva_8'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
