# Generated by Django 5.1.5 on 2025-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0026_alter_cotizaciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
