# Generated by Django 5.1.5 on 2025-03-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0028_alter_cotizaciones_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='fecha_propuesta',
            field=models.DateField(auto_now_add=True),
        ),
    ]
