# Generated by Django 5.1.5 on 2025-03-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('volumen_total', models.FloatField(blank=True, default=None, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('inventario', models.IntegerField(blank=True, null=True)),
                ('precio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('precio_distribuidor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otro', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images_products/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs')),
            ],
        ),
    ]
