# Generated by Django 5.1.5 on 2025-02-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='otro',
            field=models.BooleanField(default=False),
        ),
    ]
