# Generated by Django 5.1.5 on 2025-03-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_largo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volumen',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='volumen_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
