# Generated by Django 5.1.5 on 2025-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_alto_product_ancho_product_largo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volumen_total',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
