# Generated by Django 5.1.5 on 2025-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_volumen_alter_product_volumen_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='otro',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
