# Generated by Django 5.1.5 on 2025-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='otro',
            field=models.BooleanField(default=False),
        ),
    ]
