# Generated by Django 5.1.5 on 2025-05-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
